# Generated by Django 4.1 on 2022-08-10 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cleaning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('soap', models.CharField(max_length=1)),
                ('rock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.rock')),
            ],
        ),
    ]
