# Generated by Django 4.1 on 2022-08-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_cleaning_options_alter_cleaning_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consistency', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cleaning',
            name='soap',
            field=models.CharField(choices=[('D', 'Dove'), ('P', 'PetSmart Brand'), ('H', 'Head and Shoulders'), ('B', 'Brawny'), ('L', 'Lysol')], default='D', max_length=1),
        ),
    ]
