# Generated by Django 4.1 on 2022-08-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_rock_dirt_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dirt',
            name='consistency',
            field=models.CharField(max_length=20),
        ),
    ]
